### ISSUE TITLE
Persistent Data

### ISSUE THREAD

**Issue by maddyras** [Interactive-Phylogeny-Team/InteractivePhylogeny#14]
We discussed having a persistent data layer to the application in the form of a MongoDB. We also talked about accessing the data through a "login" screen with two options: select data table or add a new data table.

**Comment by maddyras** [comment]
We should store the DNA sequences as text strings that are limited to a set number of characters (25, for example). The json file should have an attribute associated with each species for DNA sequence that holds the plain text string.

**Comment by erikhuck** [comment]
Rather than a login screen, there could be a dropdown that specifies which type of tree the front-end needs from the back-end
