### ISSUE TITLE
Progress Report 1 - Feb 12th

### ISSUE THREAD

**Issue by jbeatty88** [Interactive-Phylogeny-Team/InteractivePhylogeny#29]
Due Feb 12th

Purpose:

To model a client/manager relationship.

Outcome:

Gain feedback on the progress of work.

Instructions:

Successful completion of this project requires planning. You should start this well in advance of the deadline.

Each group project has a steward who proposed the project. In this assignment you need to have a formal meeting with the steward and go over your team's progress. At this point in the project you have an introduction and an outline. Your progress report should go over both of these points. You should discuss what you learned in the background literature search that went into your introduction. You should discuss your outline and specifically the methods, figures and results. During the discussion, take notes. Integrate suggestions from the steward into your revised introduction/outline as necessary.

Deliverables: 

This is a group assignment; one person submits on behalf of the whole group.

Turn in a PDF of your meeting notes through LearningSuite, specifically highlighting things that the steward suggests as changes.

**Comment by sarahkateorr** [comment]
Submitted.
