### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by erikhuck** [Interactive-Phylogeny-Team/InteractivePhylogeny#3]
# Description
The assignment is listed in learning suite as "Manuscript Introduction Bullets".

# Acceptance Criteria
Completion of this learning suite assignment. Turned in by one of us.

**Comment by erikhuck** [comment]
We can probably create this assignment in a google doc. After we create one, I'll post the share link of it in the description. It might also be a good idea to have a separate doc tracking the papers we're reading so that we can compile our list of citations. This document could have the link to the manuscript along with notes about the paper, separated by bullet points. Not all of the papers listed in this doc would necessarily be cited in our paper, but we could select the relevant ones. If we decide to make this doc as well, I'll post the share link to it in this issue as well.

**Comment by sarahkateorr** [comment]
Here is the link to the Outline. It is still in it's early stages but I'll continue working on it over the weekend. I would love any suggestions or help if anyone would like to add. I have specific questions/concerns highlighted in yellow. 
https://docs.google.com/document/d/16Bs14prxxc1JJREFavC7CzvPd-lu8xVI9L5EL9ek0XM/edit?usp=sharing

**Comment by jbeatty88** [comment]
Wow, this is super awesome! I suggested some edits on the doc and made a comment here and there. Feel free to reject any of my suggested edits if they don't make sense. Great job! @sarahkateorr
