### ISSUE TITLE
Progress Report 2 - March 26th

### ISSUE THREAD

**Issue by jbeatty88** [Interactive-Phylogeny-Team/InteractivePhylogeny#30]
Due March 19th

Purpose:

To model a client/manager relationship.

Outcome:

Gain feedback on the progress of work.

Instructions:

Each group project has a steward who proposed the project. In this assignment you need to have a formal meeting with the steward and go over your team's progress. At this point in the project you have nearly completed the project. Your progress report should go over all of your results and figures. During the discussion, take notes. Integrate suggestions from the steward into your revised manuscript as necessary.

Deliverables:

This is a group assignment; one person submits on behalf of the whole group.

Turn in a PDF of your meeting notes through LearningSuite, specifically highlighting things that the steward suggests as changes.

**Comment by erikhuck** [comment]
We'll meet with our steward on next Thursday in class

**Comment by erikhuck** [comment]
1. Show the app: Node Info view, Species information, DNA comparisons
2. Make Sure to emphasize species image, location data (map link), DNA, simple UI
2. Figure 1
3. Figure 2
4. Figure 3
5. Point out the ability to upload your own data is one of the things that might not get done

**Comment by jbeatty88** [comment]
@sarahkateorr has submitted this. 🙏
