### ISSUE TITLE
Domain Name

### ISSUE THREAD

**Issue by erikhuck** [Interactive-Phylogeny-Team/InteractivePhylogeny#4]
### Description
We need a domain name for our website which is standard practice, otherwise users would need to type in the IP address and port into the web browser to access our app. https://www.namecheap.com/ is an easy way to do this but costs money. I'm not aware of any free option for this. We may need to discuss with our steward about they want the domain name for the web app to be obtained.

### Acceptance Criteria
We have a domain name for our web app such that we can access the app with the domain name the same way that we could access it using the IP and port.

**Comment by jbeatty88** [comment]
This is what GitHub pages is supposed to solve. 

https://pages.github.com

**Comment by jbeatty88** [comment]
The url to access our app will be https://interactive-phylogeny-team.github.io/InteractivePhylogeny/

**Comment by erikhuck** [comment]
@jbeatty88 Your URL suggests that we meet the acceptance criteria for this issue. As far as I'm concerned, we can close this issue in our next meeting.

**Comment by jbeatty88** [comment]
https://interactive-phylogeny-team.github.io/InteractivePhylogeny/
