### ISSUE TITLE
Data Collection

### ISSUE THREAD

**Issue by jbeatty88** [Interactive-Phylogeny-Team/InteractivePhylogeny#43]
@maddyras is gathering species data to construct trees.

1. Name
2. Image URL
3. Coordinates
4. DNA string

**Comment by erikhuck** [comment]
Common names will also be collected. The `name` field will be changed to `scientificName` and will be the unique identifier.

**Comment by erikhuck** [comment]
We should have at least 2 or 3 trees. The primates tree is done except for the embedded map links. 1 or 2 more tree should be made. The new list of fields are
* scientificName
* commonName
* imageUrl
* latitude
* longitude
* dnaSequence
* mapLink
