### ISSUE TITLE
Tree Page Fig 1 Feature Design Setup

### ISSUE THREAD

**Issue by jbeatty88** [Interactive-Phylogeny-Team/InteractivePhylogeny#44]
@jbeatty88 will work with the phylogenyIO base code to remove unneeded features and add the boilerplate/template for future features. Design will be changed to match our feature set for figure 1.

**Comment by erikhuck** [comment]
Summary of Feedback:
* Frame the two pages (put a border around them) making it clear that they are two different pages. Put some space between them.
* Could make an arrow going from the primates button in the first page to the second page using a format that makes it clear that the arrow is for demonstration and not part of the actual UI
* Include the upload button somehow. Maybe a message could pop up that says, "Have your own" providing the opportunity to upload your own tree.
* List (in the figure description) what the capabilities are from that page including the ability to click on the nodes and the leaves and scroll
* Maybe include the common name, perhaps in parentheses, next to the scientific name in the leaves
* The black bar on the left appears to be wasted space so maybe it should pop out and disappear by clicking a small button in the top left
* Maybe arrows pointing to components of the UI labeling what it is (in the figure, not description) such as node, leaf, branch, scroller
* Have the tree icon be a common theme so it doesn't stand out awkwardly was its isolated in one place
* If color were to be added, it could mean something, like the relationship between the nodes (stretch feature)
* More of the tree should be seen or maybe the entire tree. It'd be good to see a zoomed in part though so maybe there could be a circle around a section we'd like to show a zoomed in version of and then an additional graph which has that zoomed in portion.
