### ISSUE TITLE
Continuous Integration And Unit Tests

### ISSUE THREAD

**Issue by erikhuck** [Interactive-Phylogeny-Team/InteractivePhylogeny#6]
###Description
We should set something up to run our unit tests automatically before a pull request is merged. We should not be allowed to merge pull requests if our test suite fails for a given commit.

###Acceptance Criteria
We have decided which library to use for unit tests. The unit tests are set up in the repository with at least an example unit test. Continuous integration is set up for pull requests and pull requests are blocked if tests fail.

**Comment by jbeatty88** [comment]
@erikhuck You'll have to catch me up to speed on how we can do this. My work's DevOps team had set up our CI/CD pipeline before I started working there so I don't really have a lot of working knowledge on the subject. I would love to learn though!

Can we do this all through GitHub? Do we need to use third-party tools like Jenkins?

**Comment by erikhuck** [comment]
@jbeatty88 We can use what I believe is called a GitHub app such as Travis CI, which can be installed within GitHub so it seems that it's just being done in GitHub. We could also make use of GitHub actions. I can figure out how to do this after we have some unit tests to run.

**Comment by erikhuck** [comment]
@jbeatty88 You and I can look into this together like you suggested in the meeting today.
