### ISSUE TITLE
Download as JSON 

### ISSUE THREAD

**Issue by jbeatty88** [Interactive-Phylogeny-Team/InteractivePhylogeny#64]
# Download as JSON

## The What:
![image](https://user-images.githubusercontent.com/37627395/112561108-2a5ab600-8d9a-11eb-901c-21f0f99e4c96.png)
* On the original Phylogeny.io application, there is a functionality to export/download a tree as a JSON file. 
    * This feature was somehow broken on QuickTree by frontend updates.
* The code already exists in the program but for some reason it's not working.

## The Why 
* Plain text nexus files are refusing to display the nodeInfo information whereas JSON files are correctly rendering.
* We suspect that the issue lies in the fact the the JSON has some distinct setting in the JSON 'Settings' Object that is allowing the tree to render. If we can export the plain text nexus to a JSON file and then identify the setting that allows the tree to display nodeInfo, we can offer users to upload their own trees that renders the nodeInfo too. 

## Resources
* [This website](https://jsoneditoronline.org/beta/#) may be useful in comparing JSON files to identify which setting is our culprit.

## Relevant Screenshots
The JSON Editor site
![image](https://user-images.githubusercontent.com/37627395/112561655-3f841480-8d9b-11eb-90e1-cc0f4e38cfad.png)
The JSON button on QuickTree
![image](https://user-images.githubusercontent.com/37627395/112561725-617d9700-8d9b-11eb-8417-5d8b72a883fa.png)
The potential spot where in the *phylotree.html* file where the *broken* JSON button is being displayed
![image](https://user-images.githubusercontent.com/37627395/112561792-84a84680-8d9b-11eb-9a06-8c2828054a65.png)

## Assignees
@tachinash will be looking more into the broken JSON button/feature.
@jbeatty88 will be looking into the JSON setting that is causing the JSON tree to load.

**Comment by erikhuck** [comment]
We don't need to save it as JSON anymore because we figured out how to have nexus trees.
