### ISSUE TITLE
Backend Species Endpoint Broken by AccessionNumber Column

### ISSUE THREAD

**Issue by jbeatty88** [Interactive-Phylogeny-Team/InteractivePhylogeny#79]
## What
* I am unable to query the backend species endpoint from the application or Postman

## Steps to Replicate
1. Ensure the latest table schema is used but running `npm run migrate`
2. Start the server with `npm start`
3. Query the species endpoint with Postman or Curl with a known database entry
    * Example: `http://localhost:4000/species?scientificName=Gorilla Gorilla`

## Screenshots
![image](https://user-images.githubusercontent.com/37627395/114241567-94508f00-9946-11eb-9ace-8dca0d8451b6.png)
![image](https://user-images.githubusercontent.com/37627395/114241580-9adf0680-9946-11eb-9b03-f727a2dc6212.png)

## Notice
@erikhuck don't be alarmed, on my branch I modified line 18 in backend/api/router.js to include the error as well so I could show you what the error is.

**Comment by erikhuck** [comment]
@jbeatty88 pull from main to get the latest changes if you haven't done so already. Then run this command in the `back-end` directory.
```
npx sequelize-cli db:migrate:undo:all
```
Then run this in the same directory:
```
npm run migrate
```
Let me know if the problem persists after that.

**Comment by jbeatty88** [comment]
That fixed it @erikhuck, thanks!
