### ISSUE TITLE
Deploying GitHub Pages Branch Authentication Error

### ISSUE THREAD

**Issue by jbeatty88** [Interactive-Phylogeny-Team/InteractivePhylogeny#8]
![image](https://user-images.githubusercontent.com/37627395/104693371-c6937d00-56c6-11eb-8a9e-e2475edbe974.png)

I am certain I had the correct credentials;  this might require the organization creator to deploy.

@erikhuck when you have a chance, can you:

1. Pull the main branch
2. "npm install" to resolve dependencies
3. Verify it works with "npm start"
4. run "npm run deploy" and login with your credentials when it asks
5. If that works, I can configure the rest of the GitHub hosted page

**Comment by erikhuck** [comment]
@jbeatty88 I get this error suggesting there is no `package.json`. It also doesn't show up with `ls`. Did you not commit the `package.json` file?

**Comment by erikhuck** [comment]
@jbeatty88 Even after switching to that directory, I still get a bunch of errors after doing `npm install`. `npm start` doesn't appear to have any problems. But I get this when I do `npm run deploy`
<img width="527" alt="image" src="https://user-images.githubusercontent.com/42946548/104956206-dfcb5080-5988-11eb-80d8-f6be1ca367c9.png">

**Comment by jbeatty88** [comment]
@erikhuck My bad. I just merged the most recent package.json that has the deploy scripts.

**Comment by erikhuck** [comment]
@jbeatty88 Here's the command and the output from my terminal. It looks like it worked
![Uploading image.png…]()

**Comment by erikhuck** [comment]
In resolving this issue we've discovered that it's required that the organization creator executes the deployment. I created the organization so whenever someone needs to deploy, contact me and I'll do my very best to respond ASAP.
